/*CREATE DATABASE WEBUSERDB;
GRANT ALL PRIVILEGES ON WEBUSERDB.* TO 'root'@'%' IDENTIFIED BY 'mandal01';
GRANT ALL PRIVILEGES ON WEBUSERDB.* TO 'root'@'localhost' IDENTIFIED BY 'mandal01';

USE WEBUSERDB;
*/
CREATE TABLE USER_LOGIN (LOGIN_ID VARCHAR(10) PRIMARY KEY, PASSWORD VARCHAR(15));

