/*CREATE DATABASE WEBUSERDB;
GRANT ALL PRIVILEGES ON WEBUSERDB.* TO 'root'@'%' IDENTIFIED BY 'mandal01';
GRANT ALL PRIVILEGES ON WEBUSERDB.* TO 'root'@'localhost' IDENTIFIED BY 'mandal01';

USE WEBUSERDB;
*/
CREATE TABLE WEBUSERDB.USER_REGISTERED (LOGIN_ID VARCHAR(10) PRIMARY KEY , FIRST_NAME VARCHAR(50),LAST_NAME VARCHAR(50) );

