/*CREATE DATABASE WEBUSERDB;


USE WEBUSERDB;
*/
GRANT ALL PRIVILEGES ON WEBUSERDB.* TO 'root'@'%' IDENTIFIED BY 'mandal01';
GRANT ALL PRIVILEGES ON WEBUSERDB.* TO 'root'@'localhost' IDENTIFIED BY 'mandal01';